---
- name: mac setup
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  collections:
    - community.general
  roles:
    - homebrew
    - homebrew_cask
    - vscode_extentions
    - ghq_github
