---
- name: Setup macOS
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  collections:
    - community.general
  roles:
    - homebrew
    - homebrew_cask
    - vscode_extensions
    - ghq_github
