---
items:
  - aaron-bond.better-comments
  - alefragnani.Bookmarks
  - AmazonWebServices.aws-toolkit-vscode
  - Arjun.swagger-viewer
  - bierner.markdown-mermaid
  - bpruitt-goddard.mermaid-markdown-syntax-highlighting
  - BriteSnow.vscode-toggle-quotes
  - bscan.perlnavigator
  - castwide.solargraph
  - christian-kohler.path-intellisense
  - chrmarti.regex
  - DavidAnson.vscode-markdownlint
  - davidhouchin.whitespace-plus
  - dariofuzinato.vue-peek
  - dbaeumer.vscode-eslint
  - denoland.vscode-deno
  - eamodio.gitlens
  - esbenp.prettier-vscode
  - fnando.linter
  - formulahendry.code-runner
  - groksrc.ruby
  - GitHub.github-vscode-theme
  - GitHub.remotehub
  - GitHub.vscode-github-actions
  - GitHub.vscode-pull-request-github
  - GitLab.gitlab-workflow
  - Gruntfuggly.todo-tree
  - HashiCorp.terraform
  - hediet.vscode-drawio
  - IBM.output-colorizer
  - ionutvmi.path-autocomplete
  - JakeBecker.elixir-ls
  - janisdd.vscode-edit-csv
  - jebbs.plantuml
  - jeff-hykin.better-perl-syntax
  - johnpapa.vscode-peacock
  - kamikillerto.vscode-colorize
  - marp-team.marp-vscode
  - mechatroner.rainbow-csv
  - misogi.ruby-rubocop
  - mizchi.markdown-code-features
  - mosapride.zenkaku
  - ms-azuretools.vscode-docker
  - ms-vscode.vscode-typescript-next
  - ms-vscode-remote.remote-containers
  - ms-vscode-remote.remote-ssh
  - ms-vscode-remote.remote-ssh-edit
  - ms-vscode-remote.remote-wsl
  - ms-vscode-remote.vscode-remote-extensionpack
  - nemesv.copy-file-name
  - noxiz.jinja-snippets
  - oderwat.indent-rainbow
  - pflannery.vscode-versionlens
  - pnp.polacode
  - rebornix.ruby
  - redhat.ansible
  - redhat.fabric8-analytics
  - redhat.java
  - redhat.vscode-yaml
  - redhat.vscode-xml
  - rvest.vs-code-prettier-eslint
  - samosad.tt
  - samuelcolvin.jinjahtml
  - scala-lang.scala
  - scalameta.metals
  - shardulm94.trailing-spaces
  - shd101wyy.markdown-preview-enhanced
  - shibayu36.search-in-current-file
  - streetsidesoftware.code-spell-checker
  - the96.vscode-perl
  - tjmtmmnk.perl-auto-use
  - usernamehw.errorlens
  - utgwkk.perl-insert-package
  - vscjava.vscode-java-debug
  - vscjava.vscode-java-dependency
  - vscjava.vscode-java-pack
  - vscjava.vscode-java-test
  - vscjava.vscode-maven
  - vscode-icons-team.vscode-icons
  - vsls-contrib.codetour
  - Vue.volar
  - Vue.vscode-typescript-vue-plugin
  - wayou.vscode-todo-highlight
  - wingrunr21.vscode-ruby
  - yzane.markdown-pdf
  - yzhang.markdown-all-in-one
