# cSpell:disable
---
items:
  - 42Crunch.vscode-openapi
  - 766b.go-outliner
  - aaron-bond.better-comments
  - adpyke.codesnap
  - alefragnani.Bookmarks
  - alefragnani.project-manager
  - AykutSarac.jsoncrack-vscode
  - AmazonWebServices.aws-toolkit-vscode
  - amodio.restore-editors
  - antfu.goto-alias
  - antfu.slidev
  - antfu.vite
  - Arjun.swagger-viewer
  - astro-build.astro-vscode
  - bierner.emojisense
  - bierner.markdown-emoji
  - bierner.markdown-mermaid
  - bmewburn.vscode-intelephense-client
  - bpruitt-goddard.mermaid-markdown-syntax-highlighting
  - bradlc.vscode-tailwindcss
  - BriteSnow.vscode-toggle-quotes
  - bscan.perlnavigator
  - castwide.solargraph
  - christian-kohler.path-intellisense
  - chrmarti.regex
  - DavidAnson.vscode-markdownlint
  - davidhouchin.whitespace-plus
  - dariofuzinato.vue-peek
  - dbaeumer.vscode-eslint
  - denoland.vscode-deno
  - donjayamanne.githistory
  - eamodio.gitlens
  - EditorConfig.EditorConfig
  - eliostruyf.vscode-hide-comments
  - esbenp.prettier-vscode
  - exiasr.hadolint
  - fnando.linter
  - formulahendry.code-runner
  - foxundermoon.shell-format
  - groksrc.ruby
  - GitHub.github-vscode-theme
  - GitHub.remotehub
  - GitHub.vscode-github-actions
  - GitHub.vscode-pull-request-github
  - GitLab.gitlab-workflow
  - golang.Go
  - golang.go-nightly
  - Grafana.vscode-jsonnet
  - GraphQL.vscode-graphql
  - Gruntfuggly.todo-tree
  - HashiCorp.terraform
  - HashiCorp.HCL
  - hediet.vscode-drawio
  - helixquar.randomeverything
  - IBM.output-colorizer
  - ICS.japanese-proofreading
  - ionutvmi.path-autocomplete
  - JakeBecker.elixir-ls
  - janisdd.vscode-edit-csv
  - jebbs.plantuml
  - jeff-hykin.better-perl-syntax
  - johnpapa.vscode-peacock
  - joshbolduc.story-explorer
  - jrebocho.vscode-random
  - kamikillerto.vscode-colorize
  - kisstkondoros.vscode-codemetrics
  - kisstkondoros.vscode-gutter-preview
  - KevinRose.vsc-python-indent
  - leodevbro.blockman
  - Luis.console-log
  - marp-team.marp-vscode
  - mechatroner.rainbow-csv
  - Meezilla.json
  - mhutchie.git-graph
  - mishkinf.goto-next-previous-member
  - misogi.ruby-rubocop
  - mizchi.markdown-code-features
  - mosapride.zenkaku
  - ms-azuretools.vscode-docker
  - ms-playwright.playwright
  - ms-python.autopep8
  - ms-python.black-formatter
  - ms-python.debugpy
  - ms-python.flake8
  - ms-python.gather
  - ms-vscode.hexeditor
  - ms-python.isort
  - ms-python.mypy-type-checker
  - ms-python.pylint
  - ms-python.python
  - ms-python.vscode-pylance
  - ms-vscode.cmake-tools
  - ms-vscode.js-debug-nightly
  - ms-vscode.live-server
  - ms-vscode.makefile-tools
  - ms-vscode.vscode-typescript-next
  - ms-vscode.wordcount
  - ms-vscode-remote.remote-containers
  - ms-vscode-remote.remote-ssh
  - ms-vscode-remote.remote-ssh-edit
  - ms-vscode-remote.remote-wsl
  - ms-vscode-remote.vscode-remote-extensionpack
  - mxsdev.typescript-explorer
  - nemesv.copy-file-name
  - noxiz.jinja-snippets
  - Nuxtr.nuxtr-vscode
  - oderwat.indent-rainbow
  - Oracle.mysql-shell-for-vs-code
  - oven.bun-vscode
  - pflannery.vscode-versionlens
  - pmneo.tsimporter
  - pnp.polacode
  - pranaygp.vscode-css-peek
  - premparihar.gotestexplorer
  - quicktype.quicktype
  - rebornix.ruby
  - redhat.ansible
  - redhat.fabric8-analytics
  - redhat.java
  - redhat.vscode-yaml
  - ryu1kn.partial-diff
  - redhat.vscode-xml
  - rvest.vs-code-prettier-eslint
  - Rubymaniac.vscode-paste-and-indent
  - rust-lang.rust-analyzer
  - samosad.tt
  - samuelcolvin.jinjahtml
  - scala-lang.scala
  - scalameta.metals
  - shardulm94.trailing-spaces
  - shd101wyy.markdown-preview-enhanced
  - shibayu36.search-in-current-file
  - SonarSource.sonarlint-vscode
  - sorbet.sorbet-vscode-extension
  - streetsidesoftware.code-spell-checker
  - stylelint.vscode-stylelint
  - tailscale.vscode-tailscale
  - the96.vscode-perl
  - tjmtmmnk.perl-auto-use
  - usernamehw.errorlens
  - utgwkk.perl-insert-package
  - vitest.explorer
  - vscjava.vscode-gradle
  - vscjava.vscode-java-debug
  - vscjava.vscode-java-dependency
  - vscjava.vscode-java-pack
  - vscjava.vscode-java-test
  - vscjava.vscode-maven
  - vscode-icons-team.vscode-icons
  - vsls-contrib.codetour
  - Vue.volar
  - Vue.vscode-typescript-vue-plugin
  - WallabyJs.console-ninja
  - WallabyJs.quokka-vscode
  - wayou.vscode-todo-highlight
  - wingrunr21.vscode-ruby
  - wix.vscode-import-cost
  - xdebug.php-debug
  - yzane.markdown-pdf
  - yzhang.markdown-all-in-one
  - ziglang.vscode-zig
  - znck.vue
