---
items:
  - aaron-bond.better-comments
  - dariofuzinato.vue-peek
  - dbaeumer.vscode-eslint
  - esbenp.prettier-vscode
  - fnando.linter
  - JakeBecker.elixir-ls
  - janisdd.vscode-edit-csv
  - marp-team.marp-vscode
  - mosapride.zenkaku
  - ms-azuretools.vscode-docker
  - ms-vscode-remote.remote-containers
  - ms-vscode-remote.remote-ssh
  - ms-vscode-remote.remote-ssh-edit
  - ms-vscode-remote.remote-wsl
  - ms-vscode-remote.vscode-remote-extensionpack
  - oderwat.indent-rainbow
  - rvest.vs-code-prettier-eslint
  - scala-lang.scala
  - scalameta.metals
  - vscode-icons-team.vscode-icons
