---
# yamllint disable rule:truthy
name: Ansible Lint
on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install community.general
        run: ansible-galaxy collection install community.general
      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@main
