---
# yamllint disable rule:truthy
name: Ansible Lint
on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install the community general collection from Ansible Galaxy
        run: ansible-galaxy collection install community.general
      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@main
        with:
          path: mac.yml
          roles-path: ./roles:../roles:/etc/ansible/roles
